name: CD 

on:
  pull_request:
    types:
      - closed 
    branches:
      - main
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    
    #  - name: Checkout code
    #    uses: actions/checkout@v2
        
    #  - name: Setup SSH
    #    uses: webfactory/ssh-agent@v0.7.0
    #    with:
     #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      

      - name: SSH into remote server and deploy Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/peredelano-community-bot
            git pull origin main 
            docker-compose down
            docker-compose up --build -d

